### PR TITLE
CI: add publishing workflow

### LINKED ISSUE #18: Publishing Extension
Hi @waymondo 
I know that right now vscode (or this project) is not a priority for you, but it would be very helpful if you could publish the latest version to the marketplace.

I have found a github action that takes care of publishing the extensions automatically, but it needs the token associated with the account with which you published the extension the previous time.

https://github.com/HaaLeo/publish-vscode-extension

### PR DESCRIPTION
**Pull request by dubisdev**
This PR implements the [publish-vscode-extenision github workflow](https://github.com/HaaLeo/publish-vscode-extension)
closes #18 

The `VS_MARKETPLACE_TOKEN` secret must be added to this repository github secrets

### CODE REVIEW

**Comment by waymondo** [comment]
Nice. Can you bump the `package.json` version in this PR?

**Comment by dubisdev** [comment]
Yes! I just did it 🚀

**Comment by waymondo** [comment]
looks like the CI failed. I won't be at a computer until tomorrow, but I'm keen to get it figured out. thanks for this

**Comment by dubisdev** [comment]
I have not been able to see the logs, dont know what could have happened.
I will try it with some test project to see if the workflow works well

**Comment by waymondo** [comment]
I'm getting a 401 error on the publishing request being made from GitHub to the VSCode marketplace. I added a `VS_MARKETPLACE_TOKEN` secret for a Personal Access Token on my Microsoft account with 'full access'. I just added you as a collaborator to the repo if you want to take a deeper look.

**Comment by waymondo** [comment]
My first suggestion would be to fork and tweak the GH action for the publishing workflow and see if you can get better visibility into an error message besides just the unauthorized HTTP code. Let me know what you find.

**Comment by dubisdev** [comment]
I tried with another action just in case but it must be some authentication problem.
I have published another plugin with one of this actions following [this](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token) for getting the token and it worked well. 
At first there was some problem because I didn't pay attention and put the organization field wrong but as soon as I changed it it worked fine.

Anyway, although I don't have much knowledge about github actions development, I'll see if I can add a console.log somewhere to see whats happening 😎

**Comment by dubisdev** [comment]
Sorry for all the notifications that may have reached your email from the github actions :(

I have unmounted the action and finally the vsce package keeps returning a "plain" 401 error.
In the VSC documents for extension developers they link this error response to [a bad config in the token](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#i-get-403-forbidden-or-401-unauthorized-error-when-i-try-to-publish-my-extension)

Take a look at that when you can and if it doesn't work I don't know what else could be going on

**Comment by waymondo** [comment]
Not sure what I did differently the first time, but I created a new personal access token following the same instructions, updated the repo secret, and the CI action ran to completion on re-triggering.

The version just turned over on https://marketplace.visualstudio.com/items?itemName=waymondo.todoist as well.

**Pull request merged**
